CREATE DATABASE parasksdb;

CREATE USER 'vova'@'localhost' IDENTIFIED BY '123456';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, INDEX, DROP, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES ON paraskadb.* TO 'vova'@'localhost';

USE paraskadb;

CREATE TABLE tbl_employees
(
   ID INT NOT NULL AUTO_INCREMENT,
   NAME VARCHAR(100) NOT NULL,
   SALARY DECIMAL(15, 2) NOT NULL,
   CREATED_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY (ID)
);